### ISSUE TITLE
Unhandled rejection TypeError: Cannot read property 'listen' of null

### ISSUE THREAD

**Issue by bailoo** [codeforequity-at/testmybot#11]
I am following https://chatbotsmagazine.com/serverless-monitoring-of-your-facebook-chatbot-in-3-easy-steps-a051b4f248a8

My bot is live on FB messenger and I am able to run node node_modules/testmybot-chat/index.js and talk to my bot and save conversation all fine. So far so good

But when I run 
$npm test

I get this error message

> testmybot-sample-monitoring@1.0.0 test /home/tests/testmybot/samples/fbdirect
> jasmine

INFO: adding test case test2 (file: test2.convo.txt)
Started
Unhandled rejection TypeError: Cannot read property 'listen' of null
    at /home/tests/testmybot/samples/fbdirect/node_modules/testmybot/lib/testmybot-fbdirect.js:85:34
    at /home/tests/testmybot/samples/fbdirect/node_modules/testmybot/node_modules/async/dist/async.js:3853:24
    at replenish (/home/tests/testmybot/samples/fbdirect/node_modules/testmybot/node_modules/async/dist/async.js:946:17)
    at /home/tests/testmybot/samples/fbdirect/node_modules/testmybot/node_modules/async/dist/async.js:950:9
    at eachOfLimit (/home/tests/testmybot/samples/fbdirect/node_modules/testmybot/node_modules/async/dist/async.js:975:24)
    at /home/tests/testmybot/samples/fbdirect/node_modules/testmybot/node_modules/async/dist/async.js:980:16
    at _parallel (/home/tests/testmybot/samples/fbdirect/node_modules/testmybot/node_modules/async/dist/async.js:3852:5)
    at Object.series (/home/tests/testmybot/samples/fbdirect/node_modules/testmybot/node_modules/async/dist/async.js:4708:5)
    at /home/tests/testmybot/samples/fbdirect/node_modules/testmybot/lib/testmybot-fbdirect.js:78:11
    at Promise._execute (/home/tests/testmybot/samples/fbdirect/node_modules/testmybot/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/home/tests/testmybot/samples/fbdirect/node_modules/testmybot/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/home/tests/testmybot/samples/fbdirect/node_modules/testmybot/node_modules/bluebird/js/release/promise.js:79:10)
    at Object.beforeEach (/home/tests/testmybot/samples/fbdirect/node_modules/testmybot/lib/testmybot-fbdirect.js:76:10)
    at Object.beforeEach (/home/tests/testmybot/samples/fbdirect/node_modules/testmybot/lib/testmybot.js:60:20)
    at Object.<anonymous> (/home/tests/testmybot/samples/fbdirect/spec/testmybot.spec.js:10:9)
    at attemptAsync (/home/tests/testmybot/samples/fbdirect/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:3945:24)
    at QueueRunner.run (/home/tests/testmybot/samples/fbdirect/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:3884:9)
    at QueueRunner.execute (/home/tests/testmybot/samples/fbdirect/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:3872:10)
    at Spec.queueRunnerFactory (/home/tests/testmybot/samples/fbdirect/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:816:35)
    at Spec.execute (/home/tests/testmybot/samples/fbdirect/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:473:10)
    at Object.fn (/home/tests/testmybot/samples/fbdirect/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:4975:37)
    at attemptAsync (/home/tests/testmybot/samples/fbdirect/node_modules/jasmine/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:3945:24)
INFO: running testcase test2
INFO: test2 failed: nothing said in time
INFO: test2 ready, calling done function.
F

Failures:
1) TestMyBot Sample Conversation Test Suite test2
  Message:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
  Stack:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
        at ontimeout (timers.js:469:11)
        at tryOnTimeout (timers.js:304:5)
        at Timer.listOnTimeout (timers.js:264:5)
  Message:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
  Stack:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
        at ontimeout (timers.js:469:11)
        at tryOnTimeout (timers.js:304:5)
        at Timer.listOnTimeout (timers.js:264:5)
  Message:
    Failed: nothing said in time
  Stack:
    Error: Failed: nothing said in time
        at bot.setupTestSuite (/home/tests/testmybot/samples/fbdirect/spec/testmybot.spec.js:28:14)
        at async.eachSeries (/home/tests/testmybot/samples/fbdirect/node_modules/testmybot/lib/testbuilder.js:51:17)
        at /home/tests/testmybot/samples/fbdirect/node_modules/testmybot/node_modules/async/dist/async.js:421:16
        at iterateeCallback (/home/tests/testmybot/samples/fbdirect/node_modules/testmybot/node_modules/async/dist/async.js:924:17)
        at /home/tests/testmybot/samples/fbdirect/node_modules/testmybot/node_modules/async/dist/async.js:906:16
        at says.then.catch (/home/tests/testmybot/samples/fbdirect/node_modules/testmybot/lib/testbuilder.js:44:19)
        at tryCatcher (/home/tests/testmybot/samples/fbdirect/node_modules/testmybot/node_modules/bluebird/js/release/util.js:16:23)
        at Promise._settlePromiseFromHandler (/home/tests/testmybot/samples/fbdirect/node_modules/testmybot/node_modules/bluebird/js/release/promise.js:512:31)
        at Promise._settlePromise (/home/tests/testmybot/samples/fbdirect/node_modules/testmybot/node_modules/bluebird/js/release/promise.js:569:18)
        at Promise._settlePromise0 (/home/tests/testmybot/samples/fbdirect/node_modules/testmybot/node_modules/bluebird/js/release/promise.js:614:10)
        at Promise._settlePromises (/home/tests/testmybot/samples/fbdirect/node_modules/testmybot/node_modules/bluebird/js/release/promise.js:689:18)
        at Async._drainQueue (/home/tests/testmybot/samples/fbdirect/node_modules/testmybot/node_modules/bluebird/js/release/async.js:133:16)
        at Async._drainQueues (/home/tests/testmybot/samples/fbdirect/node_modules/testmybot/node_modules/bluebird/js/release/async.js:143:10)
        at Immediate.Async.drainQueues (/home/tests/testmybot/samples/fbdirect/node_modules/testmybot/node_modules/bluebird/js/release/async.js:17:14)
        at runCallback (timers.js:781:20)
        at tryOnImmediate (timers.js:743:5)

1 spec, 1 failure
Finished in 29.204 seconds

npm ERR! Test failed.  See above for more details.

**Comment by codeforequity-at** [comment]
sorry for long delay, back from summer break now. 
thanks for the submission - the sample seems not to be adapted to the latest testmybot core package version. will check it.

**Comment by codeforequity-at** [comment]
It seems that there are troubles connecting to your facebook page, and due to a bug the error message wasn't shown. with the newest commit you should now get the error message - just update your local clone of the repository and try again!
