### ISSUE TITLE
Mocha helper does not end test on failed expectation

### ISSUE THREAD

**Issue by Naktibalda** [codeforequity-at/testmybot#14]
```
INFO: Track my order failed: AssertionError: expected 'Hello. How can I help you?' to include 'Hello. How can I help you?2'
Unhandled rejection AssertionError: expect.fail()
    at testbuilder.setupTestSuite (E:\projects\botkit-starter-web\node_modules\testmybot\helper\mocha.js:16:21)
    at async.eachSeries (E:\projects\botkit-starter-web\node_modules\testmybot\lib\testbuilder.js:51:17)
```

This output is printed quickly, but the test keeps running until timeout.

**Comment by Naktibalda** [comment]
This issue is mocha specific, jasmine handles assertionError correctly.

**Comment by codeforequity-at** [comment]
Solved with latest commit!
