### ISSUE TITLE
Mocha helper does not handle rejections in readConvo method

### ISSUE THREAD

**Issue by Naktibalda** [codeforequity-at/testmybot#20]
Similar to #14, made more obvious by #19 

```
INFO: running testcase First testcase
Unhandled rejection AssertionError: Conversation is empty
    at testbuilder.setupTestSuite (E:\projects\botkit-starter-web\node_modules\testmybot\helper\mocha.js:16:21)
    at convo.readConvo.then (E:\projects\botkit-starter-web\node_modules\testmybot\lib\testbuilder.js:59:11)
...

    1) First testcase


  0 passing (1m)
  1 failing

  1) TestMyBot Test Suite for botkit-starter-web First testcase:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

**Comment by codeforequity-at** [comment]
Marked as bug.

**Comment by codeforequity-at** [comment]
Solved with latest commit!
