### ISSUE TITLE
"nothing said in time" message could be more informative.

### ISSUE THREAD

**Issue by Naktibalda** [codeforequity-at/testmybot#21]
When bot does not reply, `testmybot` fails with `nothing said in time` error.

Example of output:
```
INFO: running testcase TESTCASE NAME
INFO: TESTCASE NAME failed: nothing said in time
    1) TESTCASE NAME


  0 passing (5s)
  1 failing

  1) TestMyBot Test Suite for botkit-starter-web TESTCASE NAME:
     Error: done() invoked with non-Error: nothing said in time
      at async.eachSeries (node_modules\testmybot\lib\testbuilder.js:54:15)
```

To figure out at what point it failed, I have to run with DEBUG flag.
Then I get the following output:
```
INFO: running testcase TESTCASE NAME
DEBUG: TESTCASE NAME: hears Your service is terrible.
DEBUG: TESTCASE NAME: wait for says (channel: null)
DEBUG: TESTCASE NAME: says I'm sorry to hear you're not happy.
DEBUG: TESTCASE NAME: wait for says (channel: null)
INFO: TESTCASE NAME: nothing said in time
    1) TESTCASE NAME


  0 passing (5s)
  1 failing

  1) TestMyBot Test Suite for botkit-starter-web TESTCASE NAME:
     Error: done() invoked with non-Error: nothing said in time
      at async.eachSeries (node_modules\testmybot\lib\testbuilder.js:54:15)
```

It would be better to add an expected response to the error message:
`nothing said in time, expected 'Have a nice day'`.

**Comment by codeforequity-at** [comment]
Agree.
