### ISSUE TITLE
Issue with docker

### ISSUE THREAD

**Issue by Abgaryan** [codeforequity-at/testmybot#29]
docker-compose -p facebook_messenger_bot_with_botkit -f ./node_modules/testmybot/docker-compose.testmybot.yml -f ./node_modules/testmybot-fbmock/docker-compose.testmybot-fbmock.yml -f ./docker-compose.testmybot.override.yml kill
INFO: docker-compose exited with code 1

**Comment by codeforequity-at** [comment]
Please enable Debug-Mode (setting DEBUG environment variable to "true" - "export DEBUG=true") and run it again. it will show some hints why docker-compose fails.

**Comment by Abgaryan** [comment]
Where should I set variable true ?

**Comment by codeforequity-at** [comment]
in command line, just before running your tests - "export DEBUG=true" should do (if you are on Linux)

**Comment by Abgaryan** [comment]
I

I have this output after Exit code 1
Unhandled rejection Socket not online

Unhandled rejection Error: nothing said in time
    at bot.says.then.catch (/Users/Abgaryan/Documents/clubglobalsbot/CG-Bot-2017/spec/testmybot.spec.js:31:19)
    at tryCatcher (/Users/Abgaryan/Documents/clubglobalsbot/CG-Bot-2017/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/Abgaryan/Documents/clubglobalsbot/CG-Bot-2017/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/Abgaryan/Documents/clubglobalsbot/CG-Bot-2017/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/Abgaryan/Documents/clubglobalsbot/CG-Bot-2017/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/Abgaryan/Documents/clubglobalsbot/CG-Bot-2017/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/Users/Abgaryan/Documents/clubglobalsbot/CG-Bot-2017/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/Abgaryan/Documents/clubglobalsbot/CG-Bot-2017/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/Abgaryan/Documents/clubglobalsbot/CG-Bot-2017/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)

**Comment by Abgaryan** [comment]
@codeforequity-at  Can you take look on outputs please ?

**Comment by codeforequity-at** [comment]
Your docker-compose.testmybot.override.yml file has wrong syntax. It is not allowed to use "\t"-character there (tab), you have to use spaces.

**Comment by Abgaryan** [comment]
Aagin there is an issue 
INFO: adding test case should answer to postback (file: should_answer_to_postback.convo.txt)
Started
DEBUG: {
  "testendpoint": "http://127.0.0.1:46199",
  "defaultsaytimeout": 5000,
  "startupphase": 0,
  "containermode": "docker",
  "fbdirect": {
    "pageid": "",
    "fbuser": "",
    "fbpassword": ""
  },
  "docker": {
    "dockercomposepath": "docker-compose",
    "container": {
      "testmybot": {
        "run": true,
        "dockercomposeorder": 10,
        "dockercomposefile": "./node_modules/testmybot/docker-compose.testmybot.yml"
      },
      "testmybot-fbmock": {
        "run": true,
        "dockercomposeorder": 20,
        "dockercomposefile": "./node_modules/testmybot-fbmock/docker-compose.testmybot-fbmock.yml"
      },
      "testmybot-slackmock": {
        "run": false,
        "dockercomposeorder": 20,
        "dockercomposefile": "./node_modules/testmybot-slackmock/docker-compose.testmybot-slackmock.yml"
      }
    }
  }
}
INFO: Running Docker Command: docker-compose -p facebook_messenger_bot_with_botkit --verbose -f ./node_modules/testmybot/docker-compose.testmybot.yml -f ./node_modules/testmybot-fbmock/docker-compose.testmybot-fbmock.yml -f ./docker-compose.testmybot.override.yml kill
compose.config.config.find: Using configuration files: ././node_modules/testmybot/docker-compose.testmybot.yml,././node_modules/testmybot-fbmock/docker-compose.testmybot-fbmock.yml,././docker-compose.testmybot.override.yml
docker.auth.find_config_file: Trying paths: ['/Users/Abgaryan/.docker/config.json', '/Users/Abgaryan/.dockercfg']
docker.auth.find_config_file: Found file at path: /Users/Abgaryan/.docker/config.json
docker.auth.load_config: Couldn't find 'auths' or 'HttpHeaders' sections
docker.auth.parse_auth: Auth data for {0} is absent. Client might be using a credentials store instead.
compose.cli.command.get_client: docker-compose version 1.16.1, build 6d1ac21
docker-py version: 2.5.1
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
compose.cli.command.get_client: Docker base_url: http+docker://localunixsocket
compose.cli.command.get_client: Docker version: KernelVersion=4.9.49-moby, Arch=amd64, BuildTime=2017-09-26T22:45:38.000000000+00:00, ApiVersion=1.32, Version=17.09.0-ce, MinAPIVersion=1.12, GitCommit=afdb6d4, Os=linux, Experimental=True, GoVersion=go1.8.3
compose.cli.verbose_proxy.proxy_callable: docker containers <- (all=False, filters={u'label': [u'com.docker.compose.project=facebookmessengerbotwithbotkit', u'com.docker.compose.oneoff=False']})
compose.cli.verbose_proxy.proxy_callable: docker containers -> (list with 0 items)
compose.parallel.feed_queue: Pending: set([])
INFO: docker-compose exited with code 0
INFO: Running Docker Command: docker-compose -p facebook_messenger_bot_with_botkit --verbose -f ./node_modules/testmybot/docker-compose.testmybot.yml -f ./node_modules/testmybot-fbmock/docker-compose.testmybot-fbmock.yml -f ./docker-compose.testmybot.override.yml down
compose.config.config.find: Using configuration files: ././node_modules/testmybot/docker-compose.testmybot.yml,././node_modules/testmybot-fbmock/docker-compose.testmybot-fbmock.yml,././docker-compose.testmybot.override.yml
docker.auth.find_config_file: Trying paths: ['/Users/Abgaryan/.docker/config.json', '/Users/Abgaryan/.dockercfg']
docker.auth.find_config_file: Found file at path: /Users/Abgaryan/.docker/config.json
docker.auth.load_config: Couldn't find 'auths' or 'HttpHeaders' sections
docker.auth.parse_auth: Auth data for {0} is absent. Client might be using a credentials store instead.
compose.cli.command.get_client: docker-compose version 1.16.1, build 6d1ac21
docker-py version: 2.5.1
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
compose.cli.command.get_client: Docker base_url: http+docker://localunixsocket
compose.cli.command.get_client: Docker version: KernelVersion=4.9.49-moby, Arch=amd64, BuildTime=2017-09-26T22:45:38.000000000+00:00, ApiVersion=1.32, Version=17.09.0-ce, MinAPIVersion=1.12, GitCommit=afdb6d4, Os=linux, Experimental=True, GoVersion=go1.8.3
compose.cli.verbose_proxy.proxy_callable: docker containers <- (all=False, filters={u'label': [u'com.docker.compose.project=facebookmessengerbotwithbotkit']})
compose.cli.verbose_proxy.proxy_callable: docker containers -> (list with 0 items)
compose.parallel.feed_queue: Pending: set([])
compose.cli.verbose_proxy.proxy_callable: docker containers <- (all=False, filters={u'label': [u'com.docker.compose.project=facebookmessengerbotwithbotkit', u'com.docker.compose.oneoff=False']})
compose.cli.verbose_proxy.proxy_callable: docker containers -> (list with 0 items)
compose.cli.verbose_proxy.proxy_callable: docker containers <- (all=True, filters={u'label': [u'com.docker.compose.project=facebookmessengerbotwithbotkit']})
compose.cli.verbose_proxy.proxy_callable: docker containers -> (list with 0 items)
compose.parallel.feed_queue: Pending: set([])
compose.network.remove: Removing network facebookmessengerbotwithbotkit_default
compose.cli.verbose_proxy.proxy_callable: docker remove_network <- (u'facebookmessengerbotwithbotkit_default')
WARNING: compose.network.remove: Network facebookmessengerbotwithbotkit_default not found.
INFO: docker-compose exited with code 0
INFO: Running Docker Command: docker-compose -p facebook_messenger_bot_with_botkit --verbose -f ./node_modules/testmybot/docker-compose.testmybot.yml -f ./node_modules/testmybot-fbmock/docker-compose.testmybot-fbmock.yml -f ./docker-compose.testmybot.override.yml build
compose.config.config.find: Using configuration files: ././node_modules/testmybot/docker-compose.testmybot.yml,././node_modules/testmybot-fbmock/docker-compose.testmybot-fbmock.yml,././docker-compose.testmybot.override.yml
docker.auth.find_config_file: Trying paths: ['/Users/Abgaryan/.docker/config.json', '/Users/Abgaryan/.dockercfg']
docker.auth.find_config_file: Found file at path: /Users/Abgaryan/.docker/config.json
docker.auth.load_config: Couldn't find 'auths' or 'HttpHeaders' sections
docker.auth.parse_auth: Auth data for {0} is absent. Client might be using a credentials store instead.
compose.cli.command.get_client: docker-compose version 1.16.1, build 6d1ac21
docker-py version: 2.5.1
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
compose.cli.command.get_client: Docker base_url: http+docker://localunixsocket
compose.cli.command.get_client: Docker version: KernelVersion=4.9.49-moby, Arch=amd64, BuildTime=2017-09-26T22:45:38.000000000+00:00, ApiVersion=1.32, Version=17.09.0-ce, MinAPIVersion=1.12, GitCommit=afdb6d4, Os=linux, Experimental=True, GoVersion=go1.8.3
compose.service.build: Building testmybot-fbmock
compose.cli.verbose_proxy.proxy_callable: docker build <- (nocache=False, pull=False, cache_from=None, target=None, stream=True, labels=None, network_mode=None, tag=u'facebookmessengerbotwithbotkit_testmybot-fbmock', buildargs={}, forcerm=False, rm=True, path='/Users/Abgaryan/Documents/ClubGlobals Project/clubglobalsbot/CG-Bot-2017/node_modules/testmybot-fbmock', dockerfile='./Dockerfile')
docker.api.build._set_auth_headers: Looking for auth config
docker.api.build._set_auth_headers: Sending auth config (u'auths')
compose.cli.verbose_proxy.proxy_callable: docker build -> <generator object _stream_helper at 0x1071b51e0>
Step 1/4 : FROM node:boron
 ---> e8c6ec267732
Step 2/4 : VOLUME /usr/src/app
 ---> Using cache
 ---> 2b8df9585e20
Step 3/4 : WORKDIR /usr/src/app/node_modules/testmybot-fbmock
 ---> Using cache
 ---> 71e0c2eef601
Step 4/4 : CMD node index.js
 ---> Using cache
 ---> 5513322a6362
Successfully built 5513322a6362
Successfully tagged facebookmessengerbotwithbotkit_testmybot-fbmock:latest
compose.cli.verbose_proxy.proxy_callable: docker close <- ()
compose.cli.verbose_proxy.proxy_callable: docker close -> None
compose.service.build: Building testmybot
compose.cli.verbose_proxy.proxy_callable: docker build <- (nocache=False, pull=False, cache_from=None, target=None, stream=True, labels=None, network_mode=None, tag=u'facebookmessengerbotwithbotkit_testmybot', buildargs={}, forcerm=False, rm=True, path='/Users/Abgaryan/Documents/ClubGlobals Project/clubglobalsbot/CG-Bot-2017/node_modules/testmybot', dockerfile='./Dockerfile.testmybot')
docker.api.build._set_auth_headers: Looking for auth config
docker.api.build._set_auth_headers: Sending auth config (u'auths')
compose.cli.verbose_proxy.proxy_callable: docker build -> <generator object _stream_helper at 0x1070afb90>
Step 1/4 : FROM node:boron
 ---> e8c6ec267732
Step 2/4 : VOLUME /usr/src/app
 ---> Using cache
 ---> 2b8df9585e20
Step 3/4 : WORKDIR /usr/src/app
 ---> Using cache
 ---> cc2683791ce2
Step 4/4 : CMD npm run-script start_testmybot
 ---> Using cache
 ---> 57223719e053
Successfully built 57223719e053
Successfully tagged facebookmessengerbotwithbotkit_testmybot:latest
compose.cli.verbose_proxy.proxy_callable: docker close <- ()
compose.cli.verbose_proxy.proxy_callable: docker close -> None
INFO: docker-compose exited with code 0
Unhandled rejection Socket not online

Unhandled rejection Error: nothing said in time
    at bot.says.then.catch (/Users/Abgaryan/Documents/ClubGlobals Project/clubglobalsbot/CG-Bot-2017/spec/testmybot.spec.js:31:19)
    at tryCatcher (/Users/Abgaryan/Documents/ClubGlobals Project/clubglobalsbot/CG-Bot-2017/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/Abgaryan/Documents/ClubGlobals Project/clubglobalsbot/CG-Bot-2017/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/Abgaryan/Documents/ClubGlobals Project/clubglobalsbot/CG-Bot-2017/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/Abgaryan/Documents/ClubGlobals Project/clubglobalsbot/CG-Bot-2017/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/Abgaryan/Documents/ClubGlobals Project/clubglobalsbot/CG-Bot-2017/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/Users/Abgaryan/Documents/ClubGlobals Project/clubglobalsbot/CG-Bot-2017/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/Abgaryan/Documents/ClubGlobals Project/clubglobalsbot/CG-Bot-2017/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/Abgaryan/Documents/ClubGlobals Project/clubglobalsbot/CG-Bot-2017/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)

FUnhandled rejection Socket not online

Unhandled rejection Error: nothing said in time
    at bot.says.then.catch (/Users/Abgaryan/Documents/ClubGlobals Project/clubglobalsbot/CG-Bot-2017/spec/testmybot.spec.js:45:19)
    at tryCatcher (/Users/Abgaryan/Documents/ClubGlobals Project/clubglobalsbot/CG-Bot-2017/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/Abgaryan/Documents/ClubGlobals Project/clubglobalsbot/CG-Bot-2017/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/Abgaryan/Documents/ClubGlobals Project/clubglobalsbot/CG-Bot-2017/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/Abgaryan/Documents/ClubGlobals Project/clubglobalsbot/CG-Bot-2017/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/Abgaryan/Documents/ClubGlobals Project/clubglobalsbot/CG-Bot-2017/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/Users/Abgaryan/Documents/ClubGlobals Project/clubglobalsbot/CG-Bot-2017/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/Abgaryan/Documents/ClubGlobals Project/clubglobalsbot/CG-Bot-2017/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/Abgaryan/Documents/ClubGlobals Project/clubglobalsbot/CG-Bot-2017/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)

FINFO: running testcase should answer to postback
DEBUG: should answer to postback: hears Hallo
INFO: should answer to postback failed: Socket not online
INFO: should answer to postback ready, calling done function.
F

Failures:
1) TestMyBot Sample Conversation Test Suite should answer to hello
  Message:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
  Stack:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
        at ontimeout (timers.js:380:14)
        at tryOnTimeout (timers.js:244:5)
        at Timer.listOnTimeout (timers.js:214:5)

2) TestMyBot Sample Conversation Test Suite should send a generic payload
  Message:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
  Stack:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
        at ontimeout (timers.js:380:14)
        at tryOnTimeout (timers.js:244:5)
        at Timer.listOnTimeout (timers.js:214:5)

3) TestMyBot Sample Conversation Test Suite should answer to postback
  Message:
    Failed: Socket not online
  Stack:
    Error: Failed: Socket not online
        at testbuilder.setupTestSuite (/Users/Abgaryan/Documents/ClubGlobals Project/clubglobalsbot/CG-Bot-2017/node_modules/testmybot/helper/jasmine.js:15:14)
        at async.eachSeries (/Users/Abgaryan/Documents/ClubGlobals Project/clubglobalsbot/CG-Bot-2017/node_modules/testmybot/lib/testbuilder.js:51:17)
        at /Users/Abgaryan/Documents/ClubGlobals Project/clubglobalsbot/CG-Bot-2017/node_modules/async/dist/async.js:473:16
        at iterateeCallback (/Users/Abgaryan/Documents/ClubGlobals Project/clubglobalsbot/CG-Bot-2017/node_modules/async/dist/async.js:976:17)
        at /Users/Abgaryan/Documents/ClubGlobals Project/clubglobalsbot/CG-Bot-2017/node_modules/async/dist/async.js:958:16
        at tryCatcher (/Users/Abgaryan/Documents/ClubGlobals Project/clubglobalsbot/CG-Bot-2017/node_modules/bluebird/js/release/util.js:16:23)
        at Promise._settlePromiseFromHandler (/Users/Abgaryan/Documents/ClubGlobals Project/clubglobalsbot/CG-Bot-2017/node_modules/bluebird/js/release/promise.js:512:31)
        at Promise._settlePromise (/Users/Abgaryan/Documents/ClubGlobals Project/clubglobalsbot/CG-Bot-2017/node_modules/bluebird/js/release/promise.js:569:18)
        at Promise._settlePromise0 (/Users/Abgaryan/Documents/ClubGlobals Project/clubglobalsbot/CG-Bot-2017/node_modules/bluebird/js/release/promise.js:614:10)
        at Promise._settlePromises (/Users/Abgaryan/Documents/ClubGlobals Project/clubglobalsbot/CG-Bot-2017/node_modules/bluebird/js/release/promise.js:689:18)

3 specs, 3 failures
Finished in 73.101 seconds

**Comment by codeforequity-at** [comment]
It seems as if the setup phase is not completed - the docker containers are not started.
Just to make sure that we are up-to-date, can you please update your local testmybot repository.

**Comment by Abgaryan** [comment]
Local testmybot repository  is updated. But the issue still exists.

**Comment by codeforequity-at** [comment]
Are you running one of the samples ?

Let's start with one of them - samples/botkit/jsamine/ contains an example without docker, to make sure that TestMyBot itself is working - change to this directory, then do an "npm install" and then "node jasmine.js" 

Then an example with docker - samples\facebook, run "npm install" and then "jasmine" and lets see what happens

**Comment by Abgaryan** [comment]
Yes I using example with docker.

**Comment by Abgaryan** [comment]
do you have time may be we can do quick skype session ?

**Comment by codeforequity-at** [comment]
what timezone are you in ?

**Comment by Abgaryan** [comment]
Central European Time ,UTC +1 ,Berlin

**Comment by codeforequity-at** [comment]
By chance, i am in berlin today in the betahaus :-) so if you manage to come there with your laptop we will be able to help directly ...

**Comment by Abgaryan** [comment]
Can you  send me time and location  to my email address :  matso@airelo.me  ?

**Comment by codeforequity-at** [comment]
Was nice to meet you.
