### ISSUE TITLE
Docker fails to boot 

### ISSUE THREAD

**Issue by abid-khan** [codeforequity-at/testmybot#6]
I am getting  below error. May be we are using  -d --rm which convicts with each other.   

`./node_modules/.bin/jasmine 
Started
INFO: Running Docker Command: docker stop testmybot
INFO: Running Docker Command: docker stop testmybot-fbmock
INFO: docker stop testmybot exited with code 0
INFO: docker stop testmybot-fbmock exited with code 0
INFO: docker network rm exited with code 0
INFO: Running Docker Command: docker network create -d bridge testmybot_network
INFO: docker network create exited with code 0
INFO: Running Docker Command: docker build -t testmybot -f ./node_modules/testmybot/Dockerfile.testmybot .
INFO: Running Docker Command: docker build -t testmybot-fbmock -f ./node_modules/testmybot-fbmock/Dockerfile ./node_modules/testmybot-fbmock/
INFO: docker build testmybot-fbmock exited with code 0
INFO: docker build testmybot exited with code 0
INFO: Running Docker Command: docker run -d --rm -e NODE_TLS_REJECT_UNAUTHORIZED=0 --name testmybot --network testmybot_network --network-alias testmybot testmybot
INFO: Running Docker Command: docker run -d --rm -p 46199:46199 -e TESTMYBOT_FACEBOOK_PUBLISHPORT=46199 -e TESTMYBOT_FACEBOOK_PAGEID= -e TESTMYBOT_FACEBOOK_USERPROFILEIDDEFAULT= -e TESTMYBOT_FACEBOOK_USERPROFILELOCALE=en_US -e TESTMYBOT_FACEBOOK_SEQNOSTART= -e TESTMYBOT_FACEBOOK_SENDDELIVERY=true -e TESTMYBOT_FACEBOOK_WEBHOOKURL= -e TESTMYBOT_FACEBOOK_WEBHOOKPORT=3000 -e TESTMYBOT_FACEBOOK_WEBHOOKPATH=facebook/receive -e TESTMYBOT_FACEBOOK_WEBHOOKHOST=testmybot -e TESTMYBOT_FACEBOOK_WEBHOOKPROTOCOL=http --name testmybot-fbmock --network testmybot_network --network-alias graph.facebook.com testmybot-fbmock
INFO: docker run testmybot exited with code 1
INFO: docker run testmybot-fbmock exited with code 1
Unhandled rejection docker run testmybot returned error code 1
`

**Comment by codeforequity-at** [comment]
hi,
the log output tells exactly what docker command failed. can you please try to run those commands in sequence in your terminal window: (in the directory where your chatbot resides):

docker network create -d bridge testmybot_network
docker build -t testmybot -f ./node_modules/testmybot/Dockerfile.testmybot .
docker run --rm -e NODE_TLS_REJECT_UNAUTHORIZED=0 --name testmybot --network testmybot_network --network-alias testmybot testmybot

it should tell you why docker refuses to start.

**Comment by abidhkhan** [comment]
Once I fire above commands in sequence, last one  give me below error,

`docker: Error response from daemon: Conflict. The name "/testmybot" is already in use by container a07aaa8bb0c9492661dc56ef7247b176afab66c5a5818d232f103f781e5c4e13. You have to remove (or rename) that container to be able to reuse that name..`

**Comment by abidhkhan** [comment]
I am also getting below error 

`INFO: docker run testmybot exited with code 1
ERROR: hears Error: Error: connect ECONNREFUSED 127.0.0.1:46199
Unhandled rejection Error: says error: Error: connect ECONNREFUSED 127.0.0.1:46199
    at bot.says.then.catch (/Users/abidkhan/Desktop/Projects/node_practice/simplebot/spec/testmybot.spec.js:28:19)
    at tryCatcher (/Users/abidkhan/Desktop/Projects/node_practice/simplebot/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/abidkhan/Desktop/Projects/node_practice/simplebot/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/abidkhan/Desktop/Projects/node_practice/simplebot/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/abidkhan/Desktop/Projects/node_practice/simplebot/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/abidkhan/Desktop/Projects/node_practice/simplebot/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/Users/abidkhan/Desktop/Projects/node_practice/simplebot/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/abidkhan/Desktop/Projects/node_practice/simplebot/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/abidkhan/Desktop/Projects/node_practice/simplebot/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)

`

Also if i have configure docker-machine  and getting below ip.

`$ docker-machine ip default
192.168.99.100`


It looks like  ip and port issue. Could you please help  on this.

**Comment by codeforequity-at** [comment]
With docker-machine, the docker VMs are actually running within another virtual machine. The docker processes cannot bind to the IP address 127.0.0.1. I experienced this issue myself when I tried to run it on an old Windows 7 laptop.

Please try this:
run "docker-machine ip default" to get the IP adress which is assigned to your docker containers. For me, this is 192.168.99.100.

Then add the setting
`"testendpoint": "http://192.168.99.100:46199",`

to the "testmybot.json" file in your project directory. The file should look something like this:

```
{
  "testendpoint": "http://192.168.99.100:46199",
  "docker": {
    "container": {
      "testmybot-fbmock": {
        "env": {
          "TESTMYBOT_FACEBOOK_WEBHOOKPORT": 5000,
          "TESTMYBOT_FACEBOOK_WEBHOOKPATH": "webhook"
        }
      }
    }
  }
}

```

**Comment by abidhkhan** [comment]
I hav done what you have suggested, however still getting same issue.

` npm test 

> simplebot@1.0.0 test /Users/abidkhan/Desktop/Projects/node_practice/simplebot
> jasmine --trace-warnings

Started
INFO: Running Docker Command: docker stop testmybot
INFO: Running Docker Command: docker stop testmybot-fbmock
INFO: docker stop testmybot-fbmock exited with code 1
INFO: docker stop testmybot exited with code 1
INFO: docker network rm exited with code 1
INFO: Running Docker Command: docker network create -d bridge testmybot_network
INFO: docker network create exited with code 0
INFO: Running Docker Command: docker build -t testmybot -f ./node_modules/testmybot/Dockerfile.testmybot .
INFO: Running Docker Command: docker build -t testmybot-fbmock -f ./node_modules/testmybot-fbmock/Dockerfile ./node_modules/testmybot-fbmock/
INFO: docker build testmybot-fbmock exited with code 0
INFO: docker build testmybot exited with code 0
INFO: Running Docker Command: docker run -d --rm -e NODE_TLS_REJECT_UNAUTHORIZED=0 --name testmybot --network testmybot_network --network-alias testmybot testmybot
INFO: Running Docker Command: docker run -d --rm -p 46199:46199 -e TESTMYBOT_FACEBOOK_PUBLISHPORT=46199 -e TESTMYBOT_FACEBOOK_PAGEID= -e TESTMYBOT_FACEBOOK_USERPROFILEIDDEFAULT= -e TESTMYBOT_FACEBOOK_USERPROFILELOCALE=en_US -e TESTMYBOT_FACEBOOK_SEQNOSTART= -e TESTMYBOT_FACEBOOK_SENDDELIVERY=true -e TESTMYBOT_FACEBOOK_WEBHOOKURL= -e TESTMYBOT_FACEBOOK_WEBHOOKPORT=5000 -e TESTMYBOT_FACEBOOK_WEBHOOKPATH=webhook -e TESTMYBOT_FACEBOOK_WEBHOOKHOST=testmybot -e TESTMYBOT_FACEBOOK_WEBHOOKPROTOCOL=http --name testmybot-fbmock --network testmybot_network --network-alias graph.facebook.com testmybot-fbmock
INFO: docker run testmybot exited with code 1
Unhandled rejection docker run testmybot returned error code 1

INFO: docker run testmybot-fbmock exited with code 1
ERROR: hears Error: Error: connect ECONNREFUSED 192.168.99.100:46199
Unhandled rejection Error: says error: Error: connect ECONNREFUSED 192.168.99.100:46199
    at bot.says.then.catch (/Users/abidkhan/Desktop/Projects/node_practice/simplebot/spec/testmybot.spec.js:28:19)
    at tryCatcher (/Users/abidkhan/Desktop/Projects/node_practice/simplebot/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/abidkhan/Desktop/Projects/node_practice/simplebot/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/abidkhan/Desktop/Projects/node_practice/simplebot/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/abidkhan/Desktop/Projects/node_practice/simplebot/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/abidkhan/Desktop/Projects/node_practice/simplebot/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/Users/abidkhan/Desktop/Projects/node_practice/simplebot/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/abidkhan/Desktop/Projects/node_practice/simplebot/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/abidkhan/Desktop/Projects/node_practice/simplebot/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)

INFO: Running Docker Command: docker stop testmybot
INFO: Running Docker Command: docker stop testmybot-fbmock
INFO: docker stop testmybot exited with code 1
Unhandled rejection docker stop testmybot returned error code 1

INFO: docker stop testmybot-fbmock exited with code 1
`

**Comment by codeforequity-at** [comment]
OK, for some reason, your docker container doesn't start.
First of all, please update to the latest version - I just published the current NPM packages.

Afterwards, please run these commands in line - the last one should fail and you will see why.

docker network create -d bridge testmybot_network
docker build -t testmybot-fbmock -f ./node_modules/testmybot-fbmock/Dockerfile ./node_modules/testmybot-fbmock/
docker run --rm -p 46199:46199 -e TESTMYBOT_FACEBOOK_PUBLISHPORT=46199 -e TESTMYBOT_FACEBOOK_PAGEID= -e TESTMYBOT_FACEBOOK_USERPROFILEIDDEFAULT= -e TESTMYBOT_FACEBOOK_USERPROFILELOCALE=en_US -e TESTMYBOT_FACEBOOK_SEQNOSTART= -e TESTMYBOT_FACEBOOK_SENDDELIVERY=true -e TESTMYBOT_FACEBOOK_WEBHOOKURL= -e TESTMYBOT_FACEBOOK_WEBHOOKPORT=5000 -e TESTMYBOT_FACEBOOK_WEBHOOKPATH=webhook -e TESTMYBOT_FACEBOOK_WEBHOOKHOST=testmybot -e TESTMYBOT_FACEBOOK_WEBHOOKPROTOCOL=http --name testmybot-fbmock --network testmybot_network --network-alias graph.facebook.com testmybot-fbmock

**Comment by codeforequity-at** [comment]
I think i found the problem. Please wait for next npm package!

**Comment by codeforequity-at** [comment]
Should be solved now. Please update NPM packages!
