### ISSUE TITLE
issue while matching boolean values

### ISSUE THREAD

**Issue by kamrinkazi** [codeforequity-at/testmybot#67]
Error logs:
```
Failures:
1) TestMyBot Test Suite for conversation Lax
  Message:
    **Expected true to contain true.**
  Stack:
    Error: Expected true to contain true.
        at matcher (/home/kamrink/Desktop/Projects/conversation/node_modules/testmybot/src/helpers/jasmine.js:12:24)
        at Convo._compareObject (/home/kamrink/Desktop/Projects/conversation/node_modules/botium-core/src/scripting/Convo.js:117:7)
        at _.forOwn (/home/kamrink/Desktop/Projects/conversation/node_modules/botium-core/src/scripting/Convo.js:109:16)
        at /home/kamrink/Desktop/Projects/conversation/node_modules/lodash/lodash.js:4917:15

1 spec, 1 failure
Finished in 0.759 seconds
```
Sample Payload:
#me
search

#bot
```
{  
   "message":{  
      "attachment":{  
         "type":"template",
         "payload":{  
            "template_type":"button",
            "text":"Ready?",
            "buttons":[  
               {  
                  "type":"web_url",
                  "url":"https://google.com",
                  "messenger_extensions":true,
                  "title":"Search"
               }
            ]
         }
      }
   }
}
```

**Comment by codeforequity-at** [comment]
confirmed, this is a bug.

**Comment by kamrinkazi** [comment]
Ok,Please let me know once it is fixed

**Comment by codeforequity-at** [comment]
Can you please get latest npm package (1.3.2) and test again.

**Comment by kamrinkazi** [comment]
It works.Thanks for the fix

**Comment by kamrinkazi** [comment]
now every test cases are getting passed. even if failed test cases :D

**Comment by codeforequity-at** [comment]
maybe same reason as #61
