### ISSUE TITLE
TypeError: listeners[msg.channelId].shift(...) is not a function

### ISSUE THREAD

**Issue by codeforequity-at** [codeforequity-at/testmybot#7]
<pre>TypeError: listeners[msg.channelId].shift(...) is not a function<br> &nbsp;
 &nbsp;at Object.push (/usr/src/app/msgqueue.js:10:37)<br> &nbsp; &nbsp;at /usr/
src/app/index.js:89:14<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/us
r/src/app/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at nex
t (/usr/src/app/node_modules/express/lib/router/route.js:137:13)<br> &nbsp; &nbs
p;at next (/usr/src/app/node_modules/express/lib/router/route.js:131:14)<br> &nb
sp; &nbsp;at next (/usr/src/app/node_modules/express/lib/router/route.js:131:14)
<br> &nbsp; &nbsp;at next (/usr/src/app/node_modules/express/lib/router/route.js
:131:14)<br> &nbsp; &nbsp;at next (/usr/src/app/node_modules/express/lib/router/
route.js:131:14)<br> &nbsp; &nbsp;at next (/usr/src/app/node_modules/express/lib
/router/route.js:131:14)<br> &nbsp; &nbsp;at next (/usr/src/app/node_modules/exp
ress/lib/router/route.js:131:14)</pre>
</body>

**Comment by codeforequity-at** [comment]
resolved
