### ISSUE TITLE
Install Errors from 1.4.6 to 1.4.8

### ISSUE THREAD

**Issue by roeintense** [codeforequity-at/testmybot#94]
Howdy. Excited to see this succeed.

I have 1.4.6 installed on one machine, and 1.4.8 on another. Can't get the test samples to fire on 1.4.8 version.

Looks like there may be a dependency conflict of some kind. Running in to these errors on attempted install from root of project. From the log file after install attempt:

```
21892 warn testmybot-sample-mocha@1.0.0 No description
21893 warn testmybot-sample-mocha@1.0.0 No repository field.
21894 verbose stack Error: ENOENT: no such file or directory, rename '/home/<redacted>/repo/testmybot/samples/mocha/node_modules/.staging/testmybot-249ec557/node_modules/@babel/code-frame' -> '/home/<redacted>/repo/testmybot/samples/mocha/node_modules/.staging/@babel/code-frame-96da444a'
21895 verbose cwd /home/<redacted>/repo/testmybot/samples/mocha
21896 verbose Linux 3.10.0-693.2.2.el7.x86_64
21897 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
21898 verbose node v8.7.0
21899 verbose npm  v6.4.1
21900 error path /home/<redacted>/repo/testmybot/samples/mocha/node_modules/.staging/testmybot-249ec557/node_modules/@babel/code-frame
21901 error code ENOENT
21902 error errno -2
21903 error syscall rename
21904 error enoent ENOENT: no such file or directory, rename '/home/<redacted>/repo/testmybot/samples/mocha/node_modules/.staging/testmybot-249ec557/node_modules/@babel/code-frame' -> '/home/<redacted>/repo/testmybot/samples/mocha/node_modules/.staging/@babel/code-frame-96da444a'
21905 error enoent This is related to npm not being able to find a file.
21906 verbose exit [ -2, true ]
```

Then afterward attempting to install from `/samples/mocha` per your instructions before running tests:

```
21954 warn testmybot-sample-mocha@1.0.0 No description
21955 warn testmybot-sample-mocha@1.0.0 No repository field.
21956 verbose stack Error: ENOENT: no such file or directory, rename '/home/<redacted>/repo/testmybot/samples/mocha/node_modules/.staging/testmybot-249ec557/node_modules/@babel/code-frame' -> '/home/<redacted>/repo/testmybot/samples/mocha/node_modules/.staging/@babel/code-frame-96da444a'
21957 verbose cwd /home/<redacted>/repo/testmybot/samples/mocha
21958 verbose Linux 3.10.0-693.2.2.el7.x86_64
21959 verbose argv "/usr/bin/node" "/usr/bin/npm" "install"
21960 verbose node v8.7.0
21961 verbose npm  v6.4.1
21962 error path /home/<redacted>/repo/testmybot/samples/mocha/node_modules/.staging/testmybot-249ec557/node_modules/@babel/code-frame
21963 error code ENOENT
21964 error errno -2
21965 error syscall rename
21966 error enoent ENOENT: no such file or directory, rename '/home/<redacted>/repo/testmybot/samples/mocha/node_modules/.staging/testmybot-249ec557/node_modules/@babel/code-frame' -> '/home/<redacted>/repo/testmybot/samples/mocha/node_modules/.staging/@babel/code-frame-96da444a'
21967 error enoent This is related to npm not being able to find a file.
21968 verbose exit [ -2, true ]
```
Then an attempt at `npm run test` after both of the install errors:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'test' ]
2 info using npm@6.4.1
3 info using node@v8.7.0
4 verbose run-script [ 'pretest', 'test', 'posttest' ]
5 info lifecycle testmybot-sample-mocha@1.0.0~pretest: testmybot-sample-mocha@1.0.0
6 info lifecycle testmybot-sample-mocha@1.0.0~test: testmybot-sample-mocha@1.0.0
7 verbose lifecycle testmybot-sample-mocha@1.0.0~test: unsafe-perm in lifecycle true
8 verbose lifecycle testmybot-sample-mocha@1.0.0~test: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/<redacted>/repo/testmybot/samples/mocha/node_modules/.bin:.:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/puppetlabs/bin
9 verbose lifecycle testmybot-sample-mocha@1.0.0~test: CWD: /home/<redacted>/repo/testmybot/samples/mocha
10 silly lifecycle testmybot-sample-mocha@1.0.0~test: Args: [ '-c', 'mocha --reporter spec --exit spec' ]
11 info lifecycle testmybot-sample-mocha@1.0.0~test: Failed to exec test script
12 verbose stack Error: testmybot-sample-mocha@1.0.0 test: `mocha --reporter spec --exit spec`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at emitTwo (events.js:125:13)
12 verbose stack     at ChildProcess.emit (events.js:213:7)
12 verbose stack     at maybeClose (internal/child_process.js:927:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
13 verbose pkgid testmybot-sample-mocha@1.0.0
14 verbose cwd /home/<redacted>/repo/testmybot/samples/mocha
15 verbose Linux 3.10.0-693.2.2.el7.x86_64
16 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "test"
17 verbose node v8.7.0
18 verbose npm  v6.4.1
19 error file sh
20 error code ELIFECYCLE
21 error errno ENOENT
22 error syscall spawn
23 error testmybot-sample-mocha@1.0.0 test: `mocha --reporter spec --exit spec`
23 error spawn ENOENT
24 error Failed at the testmybot-sample-mocha@1.0.0 test script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

**Comment by codeforequity-at** [comment]
In lots of cases it helps to remove the "node_modules" folder and the "package-lock.json" file and let npm download the dependencies again ("npm install").
